name: Build StackGame

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.1.0'

      - name: Build plugin
        run: gradle clean build --stacktrace

      - name: Upload StackGame.jar
        uses: actions/upload-artifact@v4
        with:
          name: StackGame
          path: build/libs/StackGame.jar
          if-no-files-found: error
